---
kind: Service
apiVersion: v1
metadata:
  name: tutum-helloworld-service 
spec:
  selector:
    app: tutum-helloworld
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30012
  type: LoadBalancer
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutum-helloworld-deployment 
spec:
  replicas: 5
  selector:
    matchLabels:
      app: tutum-helloworld
  template:
    metadata:
      labels:
        app: tutum-helloworld
    spec:
      containers:
        - name: tutum-helloworld-container 
          image: tutum/hello-world
          ports:
            - containerPort: 80
